common:
  version: 0.0.1
  loglevel: debug

listener:
  # 客户端链接地址
  listenaddr: "127.0.0.1:9092"
  readtimeout: 120
  istls: false
  certificate: "../../deploy/priv/cert.pem"
  privatekey: "../../deploy/priv/key.pem"

cluster:
  # 节点之间通讯地址
  name: "127.0.0.1:7072"
  # gossip监听地址
  bindaddr: "127.0.0.1"
  bindport: 8082
  seeds:
    - "127.0.0.1:8081"
    - "127.0.0.1:8082"
    - "127.0.0.1:8083"

limit:
  messagesize: 1024

storage:
  name: "fdb"
  threads: 10
  dbspace: "xpush"


cache:
  name: "mem"