common:
  version: 0.0.1
  loglevel: debug

listener:
  # 客户端链接地址
  listenaddr: "127.0.0.1:9092"
  readtimeout: 120
  istls: false
  certificate: "../../deploy/priv/cert.pem"
  privatekey: "../../deploy/priv/key.pem"

cluster:
  # 节点之间通讯地址
  name: "127.0.0.1:7072"
  # gossip监听地址
  bindaddr: "127.0.0.1"
  bindport: 8081
  seeds:
    - "127.0.0.1:8081"
    - "127.0.0.1:8082"
    - "127.0.0.1:8083"

limit:
  messagesize: 1024

storage:
  name: "mysql"
  fdb:
    threads: 10
    dbspace: "xpush"
  mysql:
    acc: "root"
    passwd: "go"
    addr: "127.0.0.1"
    port: "3306"
    database: "xpush"

cache:
  name: "redis"
  redis:
    is_cluster: false
    addr: "127.0.0.1:6379"
    password: ""
    addrs:
      - "x"
      - "x"
      - "x"
      - "x"
      - "x"
      - "x"
